/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg8puzzle;
import pkg8puzzle.Nodo;
/**
 *
 * @author enriq
 */
public class Window extends javax.swing.JFrame {
    public static String estadoInicial = "123 56478"; //"12578 346";
    public static String estadoFinal = "12345678 ";
    ArbolBusqueda a = new ArbolBusqueda(new Nodo(estadoInicial), estadoFinal);
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        Numeros = new javax.swing.JTextField();
        Resultados = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Metodos = new javax.swing.JMenu();
        Anchura = new javax.swing.JMenuItem();
        Profundidad = new javax.swing.JMenuItem();
        ProfundidadIterativa = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 300));
        setMinimumSize(new java.awt.Dimension(250, 300));
        setPreferredSize(new java.awt.Dimension(250, 300));

        Numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerosActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        Resultados.setViewportView(TextArea);

        File.setText("File");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        File.add(Salir);

        jMenuBar1.add(File);

        Metodos.setText("Metodo");

        Anchura.setText("Anchura");
        Anchura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnchuraActionPerformed(evt);
            }
        });
        Metodos.add(Anchura);

        Profundidad.setText("Profundidad");
        Profundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfundidadActionPerformed(evt);
            }
        });
        Metodos.add(Profundidad);

        ProfundidadIterativa.setText("Profundidad iterativa");
        ProfundidadIterativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfundidadIterativaActionPerformed(evt);
            }
        });
        Metodos.add(ProfundidadIterativa);

        jMenuBar1.add(Metodos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(Numeros))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_SalirActionPerformed

    private void NumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerosActionPerformed

    private void AnchuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnchuraActionPerformed
        long tiempoInicio=System.currentTimeMillis();
        String nuevoEstado= Numeros.getText() ;
        a.setRaiz(nuevoEstado, estadoFinal);
        String imprimir = a.busquedaPorAnchura();
	long tiempoFinal=System.currentTimeMillis();
	long tiempoTotal=tiempoFinal-tiempoInicio;
	System.out.println("Tiempo de ejecucion "+tiempoTotal+" milisegundos");
        String textoAImprimir = "\n"+imprimir+"\n"+nuevoEstado+"\nTiempo de ejecucion "+tiempoTotal+" milisegundos";
        TextArea.setText(textoAImprimir);
    }//GEN-LAST:event_AnchuraActionPerformed

    private void ProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfundidadActionPerformed
        long tiempoInicio=System.currentTimeMillis();
        String nuevoEstado= Numeros.getText() ;
        a.setRaiz(nuevoEstado, estadoFinal);
        String imprimir = a.busquedaPrimeroEnProfundidad();
	long tiempoFinal=System.currentTimeMillis();
	long tiempoTotal=tiempoFinal-tiempoInicio;
	System.out.println("Tiempo de ejecucion "+tiempoTotal+" milisegundos");
        String textoAImprimir = "\n"+imprimir+"\n"+nuevoEstado+"\nTiempo de ejecucion "+tiempoTotal+" milisegundos";
        TextArea.setText(textoAImprimir);        // TODO add your handling code here:
    }//GEN-LAST:event_ProfundidadActionPerformed

    private void ProfundidadIterativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfundidadIterativaActionPerformed
        long tiempoInicio=System.currentTimeMillis();
        String nuevoEstado= Numeros.getText() ;
        a.setRaiz(nuevoEstado, estadoFinal);
        String imprimir = a.busquedaProfundidadIterativa(1000);
	long tiempoFinal=System.currentTimeMillis();
	long tiempoTotal=tiempoFinal-tiempoInicio;
	System.out.println("Tiempo de ejecucion "+tiempoTotal+" milisegundos");
        String textoAImprimir = "\n"+imprimir+nuevoEstado+"\nTiempo de ejecucion "+tiempoTotal+" milisegundos";
        TextArea.setText(textoAImprimir);        // TODO add your handling code here:
    }//GEN-LAST:event_ProfundidadIterativaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Anchura;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Metodos;
    private javax.swing.JTextField Numeros;
    private javax.swing.JMenuItem Profundidad;
    private javax.swing.JMenuItem ProfundidadIterativa;
    private javax.swing.JScrollPane Resultados;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
